from __future__ import annotations

from dataclasses import dataclass

@dataclass(frozen=True)
class AnalyticDefinition:
    analytic_id: str
    title: str
    porter_area: str
    sub_area: str
    library: str
    highlightable: bool
    discovery_text: str
    rationale_text: str

_DEFINITIONS_BY_ID: dict[str, AnalyticDefinition] = {}
_ENTRIES = [
    ("G-01", "Detección de actividades de gobernanza dominantes", "Actividades de soporte", "Núcleo de gobernanza", "networkx", True, "Identificamos qué actividades de dirección, control o cumplimiento son pasos que absolutamente toda la operación debe atravesar — sin excepción y sin alternativa. No porque alguien lo decidió en un manual, sino porque así está estructurado el trabajo real de la organización.", "Trazamos todos los caminos posibles desde que llega una demanda hasta que se entrega valor al cliente. Los pasos que aparecen en el 100% de esos caminos son los dominantes. Si uno de ellos falla, no hay ruta alterna: la operación se detiene."),
    ("G-02", "Puntaje de riesgo estructural de controles", "Actividades de soporte", "Núcleo de gobernanza", "networkx", True, "Calculamos cuáles de sus controles de gobernanza son los más frágiles en términos de impacto: no los que fallan más seguido, sino los que si fallan una sola vez generan el mayor daño aguas abajo en toda la organización.", "Medimos cuántos flujos operativos pasan por cada control y si existe alguna ruta alternativa que los evite. Un control que concentra muchos flujos y no tiene alternativa es estructuralmente frágil — no importa qué tan robusto parezca en papel."),
    ("G-03", "Simulación de cascada por falla regulatoria", "Actividades de soporte", "Núcleo de gobernanza", "networkx", True, "Simulamos qué pasaría si un control regulatorio o de cumplimiento específico dejara de funcionar. El resultado muestra exactamente qué indicadores de valor para sus clientes quedarían desprotegidos como consecuencia directa.", "Seguimos hacia adelante todas las actividades que dependen del control que falló, y vemos cuáles métricas de cliente ya no tienen ninguna actividad interna que las sostenga. Es como retirar una pieza del engranaje y ver qué ruedas dejan de girar."),
    ("G-04", "Conjunto mínimo de controles para continuidad", "Actividades de soporte", "Núcleo de gobernanza", "networkx", True, "Identificamos el conjunto más pequeño posible de controles y actividades de dirección que, si se mantienen funcionando, garantizan que la operación pueda seguir entregando valor a los clientes aunque todo lo demás falle.", "Buscamos el \"corte mínimo\" del grafo: el menor número de puntos que, si se eliminan, desconectan completamente la demanda del cliente de su entrega de valor. Ese conjunto es el núcleo de gobernanza no negociable."),
    ("H-01", "Mapa de concentración de conocimiento crítico", "Actividades de soporte", "Gestión de RRHH", "networkx", True, "Encontramos qué equipos o roles concentran actividades de alto valor que nadie más en la organización sabe hacer. Estas son las personas o áreas cuya salida generaría el mayor impacto operativo inmediato.", "Revisamos qué actividades tienen un único equipo responsable y cuánto valor aportan esas actividades a los clientes. Donde la combinación es \"alta importancia + un solo responsable\", hay un riesgo de dependencia de personas que la organización generalmente no tiene documentado."),
    ("H-02", "Simulación de impacto por pérdida de equipo", "Actividades de soporte", "Gestión de RRHH", "networkx", True, "Simulamos qué pasaría si un equipo completo dejara de estar disponible — por rotación, reestructura o ausencia — y medimos qué indicadores de valor para sus clientes quedarían sin respaldo operativo.", "Retiramos del mapa de operaciones todas las actividades que ese equipo ejecuta y observamos qué métricas de cliente ya no tienen ningún proceso que las sostenga. Traduce el riesgo de talento a un número de negocio concreto."),
    ("H-03", "Equipos puente entre value streams", "Actividades de soporte", "Gestión de RRHH", "networkx", True, "Identificamos qué equipos están sirviendo como puente entre distintos flujos de valor de la organización — los que sin ellos, diferentes partes de la operación perderían coordinación entre sí.", "Medimos cuántos flujos operativos distintos dependen de cada equipo para conectarse entre sí. Los equipos que aparecen en más cruces son los conectores reales de la organización, independientemente de cómo esté dibujado el organigrama."),
    ("H-04", "Valor Shapley de capacidades de RRHH", "Actividades de soporte", "Gestión de RRHH", "itertools + networkx", False, "Calculamos cuánto contribuye cada capacidad del área de personas — onboarding, capacitación, evaluación, retención — al desempeño real de los indicadores de cliente, tomando en cuenta que muchas capacidades trabajan juntas y es difícil separar su contribución individual.", "Probamos matemáticamente todas las combinaciones posibles de capacidades y medimos qué diferencia hace cada una cuando se suma o se retira del grupo. El resultado es la contribución marginal justa de cada capacidad, sin sesgo por correlación."),
    ("T-01", "Criticidad tecnológica por sistema", "Actividades de soporte", "Desarrollo tecnológico", "networkx", True, "Ordenamos todos sus sistemas y herramientas tecnológicas según cuánto valor real soportan — no según cuánto cuestan o cuánta gente los usa, sino según qué tan importantes son las actividades operativas que dependen de ellos.", "Sumamos el valor de todas las actividades críticas que usan cada sistema. Un sistema que sostiene muchas actividades de alto impacto para el cliente recibe una puntuación alta, aunque sea una herramienta sencilla o antigua."),
    ("T-02", "Detección de dependencias tecnológicas únicas", "Actividades de soporte", "Desarrollo tecnológico", "networkx", True, "Encontramos qué sistemas tecnológicos son un punto único de falla: actividades críticas para sus clientes que dependen exclusivamente de esa herramienta y quedarían completamente paralizadas si el sistema falla, sin ninguna alternativa disponible.", "Verificamos, para cada actividad importante, si existe más de un sistema que pueda soportarla. Cuando hay una sola herramienta disponible y la actividad es crítica, cualquier interrupción tecnológica se convierte directamente en un problema para el cliente."),
    ("T-03", "Mapa de oportunidades de automatización", "Actividades de soporte", "Desarrollo tecnológico", "networkx + pandas", True, "Identificamos qué actividades de su operación tienen el mayor potencial de ser automatizadas con el menor riesgo y el mayor retorno: las que se repiten mucho, ya están soportadas por algún sistema digital y no requieren decisiones complejas para ejecutarse.", "Combinamos tres señales del mapa de operaciones: qué tan frecuente es la actividad, si ya tiene soporte tecnológico, y qué tan simple es su estructura de inputs. Las actividades que puntúan alto en los tres criterios son las más directamente automatizables."),
    ("T-04", "Factores latentes tecnología–valor (SVD)", "Actividades de soporte", "Desarrollo tecnológico", "scipy", False, "Descubrimos agrupaciones naturales entre sus sistemas tecnológicos y los resultados que más importan a sus clientes — qué conjunto de herramientas trabaja unido para sostener cada tipo de valor que entrega su organización.", "Construimos una tabla que relaciona cada sistema con cada indicador de cliente y buscamos los patrones ocultos de co-ocurrencia. Es similar a cómo un análisis de datos de ventas puede revelar qué productos se compran juntos — aquí aplicamos la misma lógica a tecnología y valor."),
    ("A-01", "Índice de concentración de suministro", "Actividades de soporte", "Abastecimiento", "networkx", True, "Calculamos qué proveedores concentran la mayor dependencia operativa — no por el volumen de compra que representan, sino por cuántas de sus actividades críticas quedarían sin suministro si ese proveedor fallara y no hubiera ninguno que lo reemplazara.", "Contamos cuántas actividades importantes del proceso dependen de cada proveedor y si existen alternativas conectadas. Un proveedor con muchas actividades críticas a su cargo y sin sustituto en el mapa es un riesgo de concentración que el contrato solo no resuelve."),
    ("A-02", "Throughput máximo de la cadena de suministro", "Actividades de soporte", "Abastecimiento", "networkx", True, "Calculamos el volumen máximo que puede mover su cadena de suministro antes de saturarse — y el punto exacto donde está la restricción que frena todo lo demás.", "Modelamos cada actividad de abastecimiento como una tubería con cierta capacidad máxima. Luego calculamos cuánto puede fluir a través de toda la red. La tubería más estrecha determina el límite del sistema completo, igual que en una cadena física."),
    ("A-03", "Simulación de falla de proveedor", "Actividades de soporte", "Abastecimiento", "networkx", True, "Simulamos qué pasaría si un proveedor específico dejara de operar de un día para otro y medimos exactamente qué indicadores de valor para sus clientes se verían afectados y en qué magnitud.", "Retiramos al proveedor del mapa operativo y observamos qué actividades quedan sin insumo y, como consecuencia, qué métricas de cliente pierden el proceso que las sostenía. Es un ejercicio de \"¿y si?\" ejecutado sobre el modelo real de la operación."),
    ("A-04", "Clusters de abastecimiento estratégico vs. operativo", "Actividades de soporte", "Abastecimiento", "python-louvain", True, "Clasificamos automáticamente a sus proveedores en grupos naturales según el rol real que juegan en su operación — cuáles son verdaderamente estratégicos porque sostienen actividades críticas en múltiples procesos, y cuáles son simplemente operativos porque cubren necesidades puntuales de bajo impacto.", "El mapa operativo revela patrones de agrupación entre proveedores y las actividades que soportan. Los proveedores que aparecen conectados a las mismas actividades críticas forman clusters naturales que indican afinidad estratégica — independientemente de la categoría de compra en el ERP."),
    ("LI-01", "Ruta crítica interna", "Actividades primarias", "Logística interna", "networkx", True, "Identificamos la cadena de pasos internos que determina cuánto tiempo mínimo tarda un insumo en estar disponible para producción — el límite que ninguna mejora de eficiencia puede superar sin rediseñar la secuencia completa.", "Calculamos el camino más largo de actividades encadenadas donde cada una debe esperar a que termine la anterior. Esa cadena es el cuello de botella temporal del proceso: optimizar cualquier actividad fuera de ella no reduce el tiempo total."),
    ("LI-02", "Cuellos de botella en flujo de materiales", "Actividades primarias", "Logística interna", "networkx", True, "Encontramos exactamente en qué punto del proceso interno de materiales se produce el mayor atasco estructural: la actividad por la que todo pasa y que, si se satura, detiene todo lo que viene después.", "Contamos cuántas rutas posibles de flujo de materiales pasan por cada actividad. La que acumula más rutas es el cuello de botella real — no porque sea lenta, sino porque todo depende de que funcione sin interrupción."),
    ("LI-03", "Puntos únicos de falla en recepción", "Actividades primarias", "Logística interna", "networkx", True, "Encontramos qué pasos del proceso de recepción y manejo interno de materiales, si fallan una sola vez, interrumpen completamente el flujo hacia producción sin que haya ningún camino alternativo disponible.", "Buscamos los pasos que funcionan como \"llaves\": si se bloquean, cortan el flujo completo. Son los candidatos más urgentes a tener un procedimiento de respaldo o redundancia, porque su falla no puede absorberse de ninguna otra forma."),
    ("O-01", "Ruta crítica de producción", "Actividades primarias", "Operaciones", "networkx", True, "Encontramos la secuencia exacta de pasos productivos que determina cuánto tiempo mínimo tarda su operación en generar valor — la cadena que ninguna optimización puede acortar sin cambiar el orden o la naturaleza de los pasos.", "Identificamos todos los pasos que deben ocurrir en serie (uno espera al otro) y calculamos cuál secuencia es la más larga. Esa es la ruta crítica: cualquier mejora fuera de ella no reduce el tiempo total de producción."),
    ("O-02", "Centralidad de controles de calidad", "Actividades primarias", "Operaciones", "networkx", True, "Detectamos qué controles de calidad están funcionando también como cuellos de botella del proceso productivo: son rigurosos en lo que verifican, pero su posición en el flujo hace que todo deba esperar por ellos.", "Medimos cuántas rutas del proceso productivo pasan por cada control de calidad. Los que concentran más rutas son los que mayor impacto tienen en la velocidad — no solo en la calidad. Ahí la inversión es en agilidad del control, no en rigor."),
    ("O-03", "Riesgo bayesiano de falla de calidad por degradación de mantenimiento", "Actividades primarias", "Operaciones", "pgmpy", False, "Calculamos qué tan probable es que un problema de calidad aparezca si se descuida el mantenimiento de un equipo o proceso específico — expresado como una probabilidad concreta, no como una intuición.", "Construimos un modelo de causa y efecto entre actividades de mantenimiento y controles de calidad, calibrado con la información de impacto que ya tiene el grafo. Luego simulamos el escenario de degradación y calculamos la probabilidad resultante, como un modelo de riesgo actuarial aplicado a la operación."),
    ("O-04", "Núcleo operativo irreducible", "Actividades primarias", "Operaciones", "networkx", True, "Identificamos el corazón operativo de su empresa: el conjunto mínimo de actividades productivas que están tan interconectadas entre sí que eliminar cualquiera de ellas desestabiliza a todas las demás. Todo lo que queda fuera de este núcleo es flexible; lo que está dentro, no.", "Buscamos el grupo de actividades donde cada una está conectada directamente a al menos otras tres del mismo grupo. Ese nivel de interconexión crea una red tan densa que no puede simplificarse sin que se rompa — es el indicador más confiable del núcleo productivo real."),
    ("LE-01", "Techo de throughput de entrega por segmento", "Actividades primarias", "Logística externa", "networkx", True, "Calculamos cuántas entregas puede absorber su sistema logístico por segmento de cliente antes de colapsar — y el paso exacto que está limitando esa capacidad máxima.", "Modelamos cada actividad de distribución como una tubería con capacidad limitada. Al calcular cuánto puede fluir a través de toda la red para cada tipo de cliente, encontramos dónde está el cuello que frena el crecimiento del volumen de entregas."),
    ("LE-02", "Ruta de mayor valor por eficiencia de entrega", "Actividades primarias", "Logística externa", "networkx", True, "Encontramos la secuencia de actividades logísticas que genera el mayor valor para el cliente por cada paso que se da — la ruta más eficiente en términos de impacto, no solo de velocidad.", "Asignamos a cada paso logístico su valor de contribución al cliente y calculamos cuál camino acumula más valor por salto. Si la ruta óptima difiere del proceso actual, los pasos que sobran son candidatos concretos a rediseñar."),
    ("LE-03", "Cobertura de momentos del cliente por actividades logísticas", "Actividades primarias", "Logística externa", "networkx", True, "Mapeamos qué momentos clave de la experiencia de sus clientes — cuando reciben su primera entrega, cuando evalúan si el servicio es confiable — tienen actividades logísticas reales que los atienden, y cuáles quedan sin respaldo operativo.", "Cruzamos el mapa de la experiencia del cliente con el mapa de actividades logísticas y medimos qué tan bien cubierto está cada momento. Un momento del cliente sin actividad interna que lo soporte es un riesgo de experiencia invisible para la organización."),
    ("LE-04", "Socios logísticos críticos sin sustituto", "Actividades primarias", "Logística externa", "networkx", True, "Identificamos qué socios de transporte o distribución son un punto único de falla en su red logística: si uno de ellos falla, no hay ningún otro socio disponible en el mapa actual que pueda absorber esa función.", "Revisamos si cada socio logístico tiene equivalentes en la red que puedan cubrir las mismas rutas o actividades. Cuando no existe ningún sustituto conectado, cualquier interrupción de ese socio se traduce directamente en incumplimiento al cliente."),
    ("MV-01", "Flujo del pipeline comercial", "Actividades primarias", "Marketing y ventas", "networkx", True, "Mapeamos todas las rutas posibles que sigue la operación comercial desde que se identifica un prospecto hasta que firma un contrato — incluyendo caminos cortos que podrían acortar el ciclo de ventas y que quizás no están siendo aprovechados.", "Rastreamos en el mapa operativo todos los caminos que conectan el primer contacto con el cliente con el cierre comercial. Los caminos más cortos que existen estructuralmente pero que no se usan sistemáticamente son oportunidades concretas de acelerar el ciclo de ventas."),
    ("MV-02", "Actividades comerciales con mayor cobertura de journey", "Actividades primarias", "Marketing y ventas", "networkx", True, "Encontramos qué actividades del proceso comercial tienen el mayor impacto sobre la experiencia total del cliente — los pasos que, bien ejecutados, mejoran simultáneamente múltiples momentos de la relación con el cliente.", "Contamos cuántos momentos distintos de la experiencia del cliente toca cada actividad comercial. Las que aparecen en más momentos son las de mayor palanca para la satisfacción general — no solo para una etapa del proceso."),
    ("MV-03", "Relevancia de actividades KAM sobre retención", "Actividades primarias", "Marketing y ventas", "pandas", True, "Calculamos cuáles actividades específicas del equipo de cuentas clave tienen el mayor impacto real en que sus clientes más importantes decidan renovar — y cuáles, aunque se ejecutan, tienen un impacto mucho menor del que se asume.", "Cruzamos el mapa de actividades KAM con el modelo de valor del cliente. El resultado muestra cuánto mueve cada actividad el indicador de retención, combinando la evidencia de entrevistas con clientes y la posición de la actividad en el flujo operativo."),
    ("MV-04", "Validación de independencia de iniciativas comerciales", "Actividades primarias", "Marketing y ventas", "pgmpy", False, "Verificamos si dos iniciativas comerciales que se están considerando simultáneamente realmente atacan problemas distintos, o si en el fondo comparten la misma causa y ejecutarlas juntas produce mucho menos que la suma de sus partes.", "Trazamos los caminos causales de cada iniciativa en el mapa operativo y verificamos si se superponen. Cuando dos iniciativas comparten una causa raíz común, resolver esa causa primero es más eficiente que ejecutar ambas en paralelo."),
    ("PV-01", "Ruta crítica de resolución de incidentes", "Actividades primarias", "Servicio postventa", "networkx", True, "Encontramos el tiempo mínimo que structuralmente tarda su organización en resolver un incidente de servicio — el límite por debajo del cual ninguna cantidad de entrenamiento o personal adicional puede bajar sin cambiar la secuencia del proceso.", "Calculamos la cadena más larga de pasos de atención que deben ocurrir en serie para resolver un problema. Esa cadena define el piso de tiempo de resolución. Si el SLA prometido al cliente está por debajo de ese piso, el proceso necesita rediseñarse, no solo ejecutarse más rápido."),
    ("PV-02", "Cuellos de botella en escalación", "Actividades primarias", "Servicio postventa", "networkx", True, "Identificamos en qué punto del proceso de atención y escalación se concentra la mayor congestión — el paso por el que deben pasar prácticamente todos los casos que se complican, creando el mayor retraso en la resolución.", "Medimos cuántos caminos distintos de escalación convergen en cada actividad de atención. La que acumula más convergencias es el cuello de botella estructural del servicio — no porque sea ineficiente, sino porque todo lo redirigen hacia ella."),
    ("PV-03", "Riesgo bayesiano de churn por degradación del servicio", "Actividades primarias", "Servicio postventa", "pgmpy", False, "Calculamos con qué probabilidad una degradación en la calidad de respuesta a incidentes se traduce en pérdida de clientes — no como suposición, sino como resultado de modelar la relación causal real entre servicio y retención en su operación.", "Construimos un modelo probabilístico basado en las relaciones causales del mapa operativo y lo calibramos con los datos de impacto que ya tiene el grafo. El resultado es una probabilidad concreta que conecta la inversión en servicio postventa con su efecto directo en retención."),
    ("PV-04", "Cobertura de momentos críticos del journey por postventa", "Actividades primarias", "Servicio postventa", "networkx + pandas", True, "Verificamos si los momentos más sensibles de la relación con su cliente — cuando reportan un problema, cuando se hace la revisión periódica y cuando deciden si renovar — tienen actividades internas concretas que los atienden, o si suceden sin que la organización haga algo específico para gestionarlos.", "Cruzamos los momentos del journey del cliente con el mapa de actividades de postventa y medimos qué tan bien cubierto está cada uno. Un momento crítico del cliente sin actividad interna asignada es una brecha de servicio que probablemente nadie ha documentado como tal."),
    ("PV-05", "Propagación de valor upstream desde éxito del cliente", "Actividades primarias", "Servicio postventa", "networkx + implementación propia", True, "Calculamos el valor que generan actividades de adopción y acompañamiento al cliente que normalmente son invisibles en los análisis convencionales — porque los clientes no las mencionan directamente pero son las que preparan el terreno para que el cliente renueve.", "Partimos del resultado que más importa — la renovación del cliente — y seguimos hacia atrás en el mapa operativo asignando una fracción del valor a cada actividad que contribuyó a llegar ahí. Las actividades de éxito del cliente aparecen así con un valor derivado que refleja su contribución real aunque sea indirecta."),
]

for _aid, _title, _pa, _sa, _lib, _hi, _disc, _rat in _ENTRIES:
    _DEFINITIONS_BY_ID[_aid] = AnalyticDefinition(
        analytic_id=_aid,
        title=_title,
        porter_area=_pa,
        sub_area=_sa,
        library=_lib,
        highlightable=_hi,
        discovery_text=_disc,
        rationale_text=_rat,
    )

ALL_ANALYTIC_DEFINITIONS: tuple[AnalyticDefinition, ...] = tuple(_DEFINITIONS_BY_ID[_aid] for _aid in sorted(_DEFINITIONS_BY_ID))

def list_analytic_ids() -> tuple[str, ...]:
    return tuple(_aid for _aid, *_ in _ENTRIES)

def get_analytic_definition(analytic_id: str) -> AnalyticDefinition:
    try:
        return _DEFINITIONS_BY_ID[analytic_id]
    except KeyError as exc:
        raise KeyError(f"Analítica desconocida: {analytic_id}") from exc
